### ISSUE TITLE
Relationship with custom scope

### ISSUE THREAD

**Issue by danilolic** [vasilakisfil/SimpleAMS#40]
Hi!
I'm migrating AMS stuff to simpleAMS. In AMS serializer I have:

```ruby
class SchoolSerializer < BaseSerializer
  attributes :id, :name

  has_many :indicators do
    object.indicators.where(active: true)
  end
end
```
That way I can customize my relationship scope. So when I try that on SimpleAMS:

```ruby
class SchoolSerializer
  include SimpleAMS::DSL
  adapter SimpleAMS::Adapters::AMS

  attributes :id, :name

  has_many :indicators, serializer: IndicatorSerializer do
    object.indicators.where(active: true)
  end
end
```
 I get 

```bash
NameError:
       undefined local variable or method `object' for SchoolSerializer::EmbeddedIndicatorsOptions_:Class
```

I know that I can get that with fields

```ruby
def indicators
  object.indicators.where(active: true)
end
```
But It can be semantically confusing since when you have a relationship you add in the _includes_ key. Any thoughts about that?

**Comment by vasilakisfil** [comment]
Hi,

I understand that coming from AMS it feels intuitive to override the relation block to specify the scope of the relation. However, SimpleAMS although it shares similarities with AMS, it supports more features than AMS. So in this case, the block of a relation represents the [embedded content](https://github.com/vasilakisfil/SimpleAMS#embedded-content-again-recursive) of a relation. Inside that block, SimpleAMS DSL is supported, recursively. Of course the use of that block depends on the adapter being used, but for JSON:API, it does that by having some links in the main body and the rest in the included section. That’s possible if you pass a block in the relation directive. For instance, for specifying some links for indicators, it could be like that:

```ruby
has_many :indicators, serializer: IndicatorsSerializer do
  #these goes to a class named `Embedded`, attached to the relation
  link :self, ->(obj){ "/api/v1/schools/#{obj.school_id}/relationships/indicators" }
  link :related, ->(obj){ ["/api/v1/schools/#{obj.school_id}", rel: :school] }
end
```

You can think the DSL of SimpleAMS as a way to specify how your API resource/document should look like. For the actual data, SimpleAMS does a favor for you to actually call `object.method` where method is either a relationship or a field defined in your document. It does this favor because 90% of the cases it's like that: the data for the serializer fields/relations can be found by calling the method of the same name (field/relation) of the serializable object.

If you need to have specific scopes etc, you should define your own methods inside the serializer. SimpleAMS was intended to be like that, I mean by design, because we prefer **clarity than magic**. Sure it could be a bit more code to write, but at least Ruby makes it easy to share common code using modules :)
